#!/usr/bin/env bash
#
# FinanceHub — provision a bare Ubuntu 24.04 VPS. No Docker.
#
# Idempotent: safe to re-run after a failure or a `git pull`. Anything already
# present is left alone; only missing pieces are created.
#
#   sudo bash deploy/provision.sh
#
# What this deliberately does NOT install
# ---------------------------------------
# Kafka. The validation pipeline runs REST-only when CONSUME_KAFKA=false
# (services/validation_pipeline/app/main.py), accepting batches on POST
# /validate instead. Dropping it removes a JVM worth roughly a gigabyte of
# RAM, which is the difference between a comfortable 4 GB box and a struggling
# one. Re-enable by installing a broker and flipping the flag in .env.
#
# Network posture
# ---------------
# Every application service binds 127.0.0.1. PostgreSQL and Redis keep their
# Ubuntu defaults, which are also loopback-only. nginx is the sole public
# surface. This matters more without Docker than with it: there is no network
# namespace here, so a service bound to 0.0.0.0 is on the internet, and an
# unauthenticated Redis on a public IP is compromised within hours.
set -euo pipefail

APP_ROOT="${APP_ROOT:-/opt/financehub}"
APP_USER="${APP_USER:-financehub}"
DB_NAME="${DB_NAME:-financehub}"
DB_USER="${DB_USER:-financehub}"
STATE_DIR="/var/lib/financehub"
NODE_MAJOR=20

log()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33m  !  %s\033[0m\n' "$*"; }

[[ $EUID -eq 0 ]] || { echo "Run with sudo." >&2; exit 1; }
[[ -f "$APP_ROOT/db/schema.sql" ]] || {
  echo "Expected the repo at $APP_ROOT (no db/schema.sql found)." >&2
  echo "  git clone <repo> $APP_ROOT && sudo bash $APP_ROOT/deploy/provision.sh" >&2
  exit 1
}

# ── Packages ─────────────────────────────────────────────────────────────
log "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  postgresql postgresql-contrib \
  redis-server \
  nginx \
  python3 python3-venv python3-dev \
  build-essential libpq-dev \
  git curl ca-certificates ufw

if ! command -v node >/dev/null || [[ "$(node -v | sed 's/v\([0-9]*\).*/\1/')" -lt "$NODE_MAJOR" ]]; then
  log "Installing Node ${NODE_MAJOR} (Ubuntu ships an older one; Vite needs 20+)"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
  apt-get install -y -qq nodejs
fi

# ── Service account ──────────────────────────────────────────────────────
if ! id -u "$APP_USER" >/dev/null 2>&1; then
  log "Creating service account $APP_USER"
  # System account, no login shell: these processes are never signed into.
  useradd --system --home-dir "$APP_ROOT" --shell /usr/sbin/nologin "$APP_USER"
fi
install -d -o "$APP_USER" -g "$APP_USER" "$STATE_DIR"

# ── Secrets ──────────────────────────────────────────────────────────────
# Generated once and never regenerated: rewriting JWT_SECRET on every run would
# invalidate every issued token, and rewriting the DB password would lock the
# services out of their own database.
if [[ ! -f "$APP_ROOT/.env" ]]; then
  log "Generating .env with fresh secrets"
  DB_PASSWORD="$(openssl rand -hex 24)"
  cat >"$APP_ROOT/.env" <<EOF
# Generated by deploy/provision.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Secrets are random per machine; none of .env.example's defaults survive here.

POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_DB=${DB_NAME}
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}

REDIS_URL=redis://127.0.0.1:6379/0
CELERY_BROKER_URL=redis://127.0.0.1:6379/1

# No broker on this host; the pipeline serves POST /validate instead.
CONSUME_KAFKA=false
KAFKA_BROKER=
KAFKA_TOPIC_RAW=raw_transactions

MATCH_CONFIDENCE_THRESHOLD=0.85
RETRAIN_TRIGGER_COUNT=200

JWT_SECRET=$(openssl rand -hex 32)
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=480
SERVICE_API_KEY=$(openssl rand -hex 24)
REQUIRE_AUTH=true

EXCEPTION_HANDLER_URL=http://127.0.0.1:8003
# Same-origin through nginx, so no cross-origin grant is needed.
CORS_ORIGINS=
LOG_LEVEL=INFO
EOF
  chmod 600 "$APP_ROOT/.env"
  chown "$APP_USER:$APP_USER" "$APP_ROOT/.env"
else
  warn ".env exists — left untouched. Delete it to regenerate secrets."
fi

# shellcheck disable=SC1090
set -a; source "$APP_ROOT/.env"; set +a

# ── PostgreSQL ───────────────────────────────────────────────────────────
log "Configuring PostgreSQL"
systemctl enable --now postgresql

role_exists=$(sudo -u postgres psql -tAc \
  "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" || true)
if [[ "$role_exists" != "1" ]]; then
  sudo -u postgres psql -qc \
    "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${POSTGRES_PASSWORD}';"
else
  # Keeps the role in step with .env when the file was regenerated.
  sudo -u postgres psql -qc \
    "ALTER ROLE ${DB_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';"
fi

db_exists=$(sudo -u postgres psql -tAc \
  "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" || true)
if [[ "$db_exists" != "1" ]]; then
  sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
  log "Applying db/schema.sql"
  # schema.sql is written to be re-runnable, but it only *needs* to run once,
  # on the empty database Docker's entrypoint would otherwise have handled.
  #
  # Applied as $APP_USER, not postgres: DB_USER owns the database, and on
  # PG15+ the owner's session gets implicit CREATE on public via
  # pg_database_owner, so objects it creates come out owned by DB_USER too.
  # Applying as postgres instead leaves every table owned by postgres —
  # GRANT ALL hands DB_USER DML rights but not ownership, so DB_USER's own
  # DATABASE_URL can never re-run schema.sql (ALTER/CREATE TRIGGER/CREATE OR
  # REPLACE FUNCTION all require owning the object), breaking the "more than
  # one path may apply it" guarantee schema.sql is written to.
  sudo -u "$APP_USER" psql -q -d "$DB_NAME" -f "$APP_ROOT/db/schema.sql"
else
  warn "Database ${DB_NAME} exists — schema not reapplied."
fi

# ── Redis ────────────────────────────────────────────────────────────────
log "Enabling Redis"
systemctl enable --now redis-server

# ── Python ───────────────────────────────────────────────────────────────
log "Building the virtualenv"
# One venv for all six processes. Verified safe: every package duplicated
# across the four requirements.txt files pins an identical version, so a merged
# install cannot resolve to something a service did not ask for.
if [[ ! -x "$APP_ROOT/.venv/bin/python" ]]; then
  python3 -m venv "$APP_ROOT/.venv"
fi
"$APP_ROOT/.venv/bin/pip" install -q --upgrade pip wheel
for req in shared services/validation_pipeline services/matching_engine \
           services/exception_handler services/reporting_api; do
  "$APP_ROOT/.venv/bin/pip" install -q -r "$APP_ROOT/$req/requirements.txt"
done

install -d -o "$APP_USER" -g "$APP_USER" \
  "$APP_ROOT/services/matching_engine/models" \
  "$APP_ROOT/services/exception_handler/models"

# ── Frontend ─────────────────────────────────────────────────────────────
log "Building the dashboard"
# VITE_ variables are read at build time, not run time, so the key has to be
# present now. It is compiled into the public bundle and readable with
# devtools — acceptable for a demo secret, and not a way to ship a credential.
cat >"$APP_ROOT/frontend/.env.production" <<EOF
VITE_API_BASE_URL=
VITE_API_TIMEOUT=12000
VITE_SERVICE_API_KEY=${SERVICE_API_KEY}
EOF
( cd "$APP_ROOT/frontend" && npm ci --no-audit --no-fund && npm run build )

install -d /var/www/financehub
rm -rf /var/www/financehub/*
cp -r "$APP_ROOT/frontend/dist/." /var/www/financehub/
chown -R www-data:www-data /var/www/financehub

# ── systemd ──────────────────────────────────────────────────────────────
log "Installing systemd units"
cp "$APP_ROOT"/deploy/systemd/*.service /etc/systemd/system/
chown -R "$APP_USER:$APP_USER" "$APP_ROOT/services" "$APP_ROOT/shared"
systemctl daemon-reload

UNITS=(
  financehub-validation
  financehub-matching
  financehub-exceptions
  financehub-reporting
  financehub-celery-worker
  financehub-celery-beat
)
systemctl enable --now "${UNITS[@]}"

# ── nginx ────────────────────────────────────────────────────────────────
log "Configuring nginx"
NGINX_SITE=/etc/nginx/sites-available/financehub

# Once certbot has run it owns this file: it adds the 443 server, the
# certificate paths and the HTTP->HTTPS redirect in place. Copying the
# repo's template over that would silently delete TLS on the next deploy and
# leave the box serving the sign-in key in clear text - the exact thing the
# certificate was obtained to prevent. Re-running provision.sh must never be
# the reason a site stops being encrypted, so the template is only installed
# when certbot has not taken over.
if [[ -f "$NGINX_SITE" ]] && grep -q "managed by Certbot" "$NGINX_SITE"; then
  warn "nginx site is certbot-managed - left untouched to preserve TLS."
  warn "  To change the proxy rules, edit deploy/nginx/financehub.conf, apply it"
  warn "  by hand, then re-run: certbot install --cert-name <your.domain> --nginx"
else
  cp "$APP_ROOT/deploy/nginx/financehub.conf" "$NGINX_SITE"
  # certbot needs a concrete server_name to find its server block; the
  # template ships the `_` catch-all so a nameless box still serves.
  if [[ -n "${SERVER_NAME:-}" ]]; then
    sed -i "s/^    server_name _;/    server_name ${SERVER_NAME};/" "$NGINX_SITE"
    log "nginx server_name set to ${SERVER_NAME}"
  fi
fi

ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/financehub
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

# ── Firewall ─────────────────────────────────────────────────────────────
log "Applying firewall rules"
ufw allow OpenSSH >/dev/null
ufw allow 'Nginx Full' >/dev/null
# Everything else stays closed. The application ports are loopback-bound
# anyway; this is the second lock, not the first.
ufw --force enable >/dev/null
ufw status verbose | sed 's/^/    /'

# ── Report ───────────────────────────────────────────────────────────────
log "Service status"
systemctl --no-pager --plain is-active "${UNITS[@]}" | paste -d' ' \
  <(printf '%s\n' "${UNITS[@]}") - | sed 's/^/    /'

cat <<EOF

$(log "Done")
    Dashboard      http://$(curl -fsS --max-time 5 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')/
    API docs       (loopback only) curl http://127.0.0.1:8000/docs
    Sign-in key    grep SERVICE_API_KEY $APP_ROOT/.env

    Seed it        sudo -u $APP_USER $APP_ROOT/.venv/bin/python \\
                     $APP_ROOT/tools/seed.py --count 2000 --sink files --out /tmp/seed
                   then POST the batches to http://127.0.0.1:8001/validate

    Logs           journalctl -u financehub-reporting -f
    Restart all    systemctl restart ${UNITS[*]}

    TLS is not configured. Before this is reachable by anyone else:
      apt install certbot python3-certbot-nginx && certbot --nginx -d your.domain
EOF
